site_name: Colacho 3.5
nav:
    - Home: index.md
    - Reglas: rules.md
    - Lugares: places.md
    - Clases:
        - class.md
        - Guerrero: c_guerrero.md
        - Bárbaro: c_barbaro.md
        - Bardo: c_bardo.md
        - Mago: c_mago.md
    - Dotes: feats.md
    - Objetos: objects.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: default
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

